### PR TITLE
Run unit tests in Travis builds

### PR DESCRIPTION
**Pull request by cmccandless**

### CODE REVIEW

**Comment by cmccandless** [comment]
@exercism/scheme this is ready for review.

**Comment by guygastineau** [comment]
Hey @cmccandless  This is some cool work!

There are some major changes coming. We will probably need to wait a bit to see exactly how to apply your work to the new structure.

I think you have accomplished the brunt of the work here, so once these new changes come into master it should be easy to modify this PR.

**Comment by guygastineau** [comment]
We are also switching to a more Scheme agnostic system, but it is being developed in `chez scheme`, so we will likely need to think about which Scheme to use in the travis build, but it should work with all of them.

**Comment by guygastineau** [comment]
So, it looks like there wont need to be a shell file to handle testing, because it will all be handled through scheme.  We will still need a travis file though :smile:

**Comment by jitwit** [comment]
Basically if you're still interested in this pull request, we'd be very happy to include it. The tricky part till be installing dependencies for travis  (srfi, guile, and chez), the easy part will be running the tests: `make`.

**Comment by cmccandless** [comment]
I am interested in adapting these changes to work with whatever is coming. Let me know when `master` is ready, and I will update this PR. Please include which scheme to run as and whatever other dependencies are needed.

**Comment by guygastineau** [comment]
Hey @cmccandless The new version is up and running.

There might end up being a couple extra things that have to happen for this to work.

Feel free to check out the new documentation, ask questions here, or you can also ask questions in the track channel on slack.

Thank you for your interest in the Scheme track! :smile:

**Comment by jitwit** [comment]
It looks like in order to run the example solutions against the tests the dependencies are:
* Make
* GNU Guile
* ChezScheme
To execute the tests:
```
make ci
```

**Comment by cmccandless** [comment]
Is there a Linux build of ChezScheme? I am unable to one in the Github releases.

**Comment by guygastineau** [comment]
@cmccandless Are the travis builds Ubuntu?

I build it from src for Arch Linux for personal use, but I checked the other day, and I thought it was available for Ubuntu

**Comment by cmccandless** [comment]
Yes, Ubuntu Xenial 16.04 is the default Linux for Travis.

**Comment by jitwit** [comment]
What about using bionic? It seems that xenial may not have it:

[https://packages.ubuntu.com/search?keywords=chezscheme](https://packages.ubuntu.com/search?keywords=chezscheme)

**Comment by guygastineau** [comment]
So at the end of the Travis log we can see that when an exercise test fails it doesn't exit with a failing status code.

It looks like everything here should be good, but we just need to exit with a non-zero status when a test fails which will happen in the scheme side of things.

**Comment by jitwit** [comment]
Two questions. Who does the error not propagate up? Also, is there a reason for specifying guile 2.0 in particular?

**Comment by guygastineau** [comment]
I am a bit confused about why the rebase thinks that this PR is adding file to the repo that already exist.

Also, @jitwit so the error from the scheme code is not causing `make` to exit with a failing status?

**Comment by cmccandless** [comment]
> Who does the error not propagate up>

I think you meant "why"? This seems to be an issue with the `make ci` target, which I was told to use, but didn't write. I can look into it, but I don't currently know what's happening there.

> Also, is there a reason for specifying guile 2.0 in particular?

I don't remember where I picked up the guile-2.0 usage. Should I just install `guile` then?

**Comment by jitwit** [comment]
Hah, why indeed :). 

Yeah, `guile` would be preferable. I think the old codebase needed 2.0 for some reason or another...

Apologies if the `make ci` target doesn't do what I intended. The scheme code throws an exception if it gets a non-zero exit when running the tests. I was assuming that it would propagate to Make

**Comment by guygastineau** [comment]
Nevermind about the diff. It fixed itself.

Oh GitHub

**Comment by jitwit** [comment]
OK, I think it will work if it's not phony. I made some adjustments that i'll bring in

**Comment by cmccandless** [comment]
From Travis:
```
Package guile is a virtual package provided by:
  guile-2.2 2.2.3+1-3ubuntu0.1
  guile-2.0 2.0.13+1-5ubuntu0.1
E: Package 'guile' has no installation candidate
```

Looks like we need to specify `guile-2.2` or `guile2.0`

**Comment by guygastineau** [comment]
I dislike Debian very much

**Comment by jitwit** [comment]
Go with 2.2, I think that's what both me and guy have as well as what most students will have

**Comment by jitwit** [comment]
This works eh? The broken part is the Makefile, which is fixed in master. Good to merge?

**Comment by guygastineau** [comment]
I guess we are lucky that Guile 2.0 was used and that it failed.  Otherwise that could have gone on as a silent bug for a while.

**Comment by jitwit** [comment]
100%! I was thinking the same. 

Great thanks for the additions!

**Pull request merged**
