### PR TITLE
Implemented two-fer exercise

### PR DESCRIPTION
**Pull request by herwinw**
This replaces the old hello-world that is simplified in #69.

### CODE REVIEW

**Comment by herwinw** [comment]
The build fails with:

```
-> An implementation for 'two-fer' was found, but config.json does not reference this exercise.
``

If someone could review the code, then I'll figure out how to update the json file

**Comment by benreyn** [comment]
Ill take a look @herwinw. Thanks for the PR!

**Comment by benreyn** [comment]
This looks good codewise @herwinw. Once we get the exercise added to `config.json` I think this should be good to merge.

**Comment by herwinw** [comment]
Well, that was about 2 minutes of work after 30 minutes of searching ([link](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md)). I've added the exercise to the bottom, it will probably need some reordering, but that should be covered in #45 since that problem is bigger than just this exercise.

**Comment by benreyn** [comment]
Thanks @herwinw!

**Pull request merged**
