### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by jitwit**

### CODE REVIEW

**Comment by guygastineau** [comment]
It would be great if non-trivial commits were up long enough for a review.

**Comment by jitwit** [comment]
Sorry. Is there anything in particular you take issue with?

**Comment by guygastineau** [comment]
No, it is nice to see progress 😁 and you are certainly leading the code production well 😁

In every track where I have taken part it is required that a maintainer (who is not the PR author) approves a commit before before it is merged (in trivial cases this rule can be ignored).

I think all the additions in this PR were steps forward, but I do think it probably should have been a couple PR's.  I recognize that this early in a total rehaul of a track it is convenient to have larger PRs with extra stuff packed in, so I would have approved it regardless.

Mostly, the docs changes needed to happen ASAP in my opinion, so just the doc changes would seem trivial enough to push through.  The code changes - though they were not large - concerned multiple parts of the tooling. Generally I am less inclined to view any code changes as trivial.

I want to be clear that I am in no way upset that you merged that PR 😁

I don't want you to have to wait long to get things merged, but I also think that if we set our conventions early then it will be easier when dealing with more contributors. So for my part, I will make sure I review/approve your PRs as soon as possible 😁 while I keep working on my parts of the project.

One thing I am going to do tonight is review the contributing doc regarding this kind of etiquette.  It think that is an important document to have nailed down for hacktober fest.

Anyway, I hope my position is clear enough.  The work was good, and my request should not indicate any problem with the quality of the PR 😁

**Comment by guygastineau** [comment]
Also, once things are a bit more settled it would be nice to use issues for tracking meaningful additions.

I will make a couple issues that I think are important tonight.

**Comment by jitwit** [comment]
Good information to know. It makes sense to make sure extra eyes look at each nontrivial change.

My thinking for pushing docs through fast was that I wanted to start getting material together on the approach to this track. Also, I realize throwing in code modifications is sloppy! Will try to avoid going ahead.

**Pull request merged**
